//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorFileSystem.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorFileSystem.Client.Resources.CommandTexts", typeof(CommandTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a watcher for target grpc service.
        /// </summary>
        internal static string Watch_Add_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Add_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify will monitor filesystem event.
        /// </summary>
        internal static string Watch_Add_Event_Description {
            get {
                return ResourceManager.GetString("Watch_Add_Event_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a regular expression of watching file or directory.
        /// </summary>
        internal static string Watch_Add_Filter_Description {
            get {
                return ResourceManager.GetString("Watch_Add_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name of will create watcher.
        /// </summary>
        internal static string Watch_Add_Name_Description {
            get {
                return ResourceManager.GetString("Watch_Add_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path of watcher will watching Path.
        /// </summary>
        internal static string Watch_Add_Path_Description {
            get {
                return ResourceManager.GetString("Watch_Add_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage watchers for remote grpc service.
        /// </summary>
        internal static string Watch_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add watching filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Add_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Add_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings a watcher watching filesystem event for target grpc service.
        /// </summary>
        internal static string Watch_Event_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Event_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Event_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of watcher to setting watching event.
        /// </summary>
        internal static string Watch_Event_Guid_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Guid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove watching filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Remove_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Remove_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Set_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Set_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show a watcher watching filesystem events.
        /// </summary>
        internal static string Watch_Event_Show_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Event_Show_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove watcher from target grpc service.
        /// </summary>
        internal static string Watch_Remove_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Remove_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of will removed watcher.
        /// </summary>
        internal static string Watch_Remove_Guid_Description {
            get {
                return ResourceManager.GetString("Watch_Remove_Guid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all watcher from target grpc service.
        /// </summary>
        internal static string Watch_Show_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Show_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a watcher from target grpc service.
        /// </summary>
        internal static string Watch_Update_Command_Description {
            get {
                return ResourceManager.GetString("Watch_Update_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify watching file system event to update watcher.
        /// </summary>
        internal static string Watch_Update_Event_Description {
            get {
                return ResourceManager.GetString("Watch_Update_Event_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify regular expression to update watcher watching file or directory.
        /// </summary>
        internal static string Watch_Update_Filter_Description {
            get {
                return ResourceManager.GetString("Watch_Update_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of will update watcher.
        /// </summary>
        internal static string Watch_Update_Guid_Description {
            get {
                return ResourceManager.GetString("Watch_Update_Guid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify a name of will update watcher.
        /// </summary>
        internal static string Watch_Update_Name_Description {
            get {
                return ResourceManager.GetString("Watch_Update_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update monitoring path of watcher.
        /// </summary>
        internal static string Watch_Update_Path_Description {
            get {
                return ResourceManager.GetString("Watch_Update_Path_Description", resourceCulture);
            }
        }
    }
}
