//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorFileSystem.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorFileSystem.Client.Resources.CommandTexts", typeof(CommandTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid of operate or chain.
        /// </summary>
        internal static string Link_Action_ArgumentDescription {
            get {
                return ResourceManager.GetString("Link_Action_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attach a operate or chain to watcher or group.
        /// </summary>
        internal static string Link_CommandDescription {
            get {
                return ResourceManager.GetString("Link_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid of watcher or group.
        /// </summary>
        internal static string Link_Monitor_ArgumentDescription {
            get {
                return ResourceManager.GetString("Link_Monitor_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a operate for target grpc service.
        /// </summary>
        internal static string Operate_Add_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Add_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new move operate for target grpc service.
        /// </summary>
        internal static string Operate_Add_Move_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Add_Move_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptive text of operate.
        /// </summary>
        internal static string Operate_Add_Move_Description_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Add_Move_Description_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when operate attached watcher watched events, will move to specify destination path.
        /// </summary>
        internal static string Operate_Add_Move_Destination_ArgumentDesciption {
            get {
                return ResourceManager.GetString("Operate_Add_Move_Destination_ArgumentDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a unpack operate, will unpack provoke filesystem event file.
        /// </summary>
        internal static string Operate_Add_Unpack_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Add_Unpack_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional description of operate.
        /// </summary>
        internal static string Operate_Add_Unpack_Description_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Add_Unpack_Description_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path of unpack destination, optional, if set will unpack content to specify path, else will unpack to file path.
        /// </summary>
        internal static string Operate_Add_Unpack_Destination_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Add_Unpack_Destination_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage operates for remote grpc service.
        /// </summary>
        internal static string Operate_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove specify operate.
        /// </summary>
        internal static string Operate_Remove_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Remove_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of will remove oeprate.
        /// </summary>
        internal static string Operate_Remove_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Remove_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all operate.
        /// </summary>
        internal static string Operate_Show_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Show_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update any specify operate description.
        /// </summary>
        internal static string Operate_Update_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Update_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update descriptive text of operate.
        /// </summary>
        internal static string Operate_Update_Description_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Description_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of will update operate.
        /// </summary>
        internal static string Operate_Update_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a move operate.
        /// </summary>
        internal static string Operate_Update_Move_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Move_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update descriptive text of operate.
        /// </summary>
        internal static string Operate_Update_Move_Description_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Move_Description_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update destination of operate.
        /// </summary>
        internal static string Operate_Update_Move_Destination_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Move_Destination_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify updating move operate.
        /// </summary>
        internal static string Operate_Update_Move_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Move_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a unpack operate.
        /// </summary>
        internal static string Operate_Update_Unpack_CommandDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Unpack_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update descriptive text of operate.
        /// </summary>
        internal static string Operate_Update_Unpack_Description_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Unpack_Description_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update destination of operate.
        /// </summary>
        internal static string Operate_Update_Unpack_Destination_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Unpack_Destination_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify updating unpack operate.
        /// </summary>
        internal static string Operate_Update_Unpack_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Operate_Update_Unpack_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a watcher for target grpc service.
        /// </summary>
        internal static string Watch_Add_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Add_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify will monitor filesystem event.
        /// </summary>
        internal static string Watch_Add_Event_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Add_Event_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a regular expression of watching file or directory.
        /// </summary>
        internal static string Watch_Add_Filter_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Add_Filter_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name of will create watcher.
        /// </summary>
        internal static string Watch_Add_Name_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Add_Name_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path of watcher will watching Path.
        /// </summary>
        internal static string Watch_Add_Path_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Add_Path_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage watchers for remote grpc service.
        /// </summary>
        internal static string Watch_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add watching filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Add_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Event_Add_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings a watcher watching filesystem event for target grpc service.
        /// </summary>
        internal static string Watch_Event_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Event_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Event_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Event_Event_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of watcher to setting watching event.
        /// </summary>
        internal static string Watch_Event_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Event_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove watching filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Remove_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Event_Remove_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a filesystem event for watcher.
        /// </summary>
        internal static string Watch_Event_Set_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Event_Set_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show a watcher watching filesystem events.
        /// </summary>
        internal static string Watch_Event_Show_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Event_Show_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove watcher from target grpc service.
        /// </summary>
        internal static string Watch_Remove_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Remove_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of will removed watcher.
        /// </summary>
        internal static string Watch_Remove_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Remove_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all watcher from target grpc service.
        /// </summary>
        internal static string Watch_Show_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Show_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a watcher from target grpc service.
        /// </summary>
        internal static string Watch_Update_CommandDescription {
            get {
                return ResourceManager.GetString("Watch_Update_CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify watching file system event to update watcher.
        /// </summary>
        internal static string Watch_Update_Event_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Update_Event_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify regular expression to update watcher watching file or directory.
        /// </summary>
        internal static string Watch_Update_Filter_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Update_Filter_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid of will update watcher.
        /// </summary>
        internal static string Watch_Update_Guid_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Update_Guid_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify a name of will update watcher.
        /// </summary>
        internal static string Watch_Update_Name_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Update_Name_ArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update monitoring path of watcher.
        /// </summary>
        internal static string Watch_Update_Path_ArgumentDescription {
            get {
                return ResourceManager.GetString("Watch_Update_Path_ArgumentDescription", resourceCulture);
            }
        }
    }
}
